# Render is a free deployement service whose servers spin down every 15mins due to free tier. To keep the server active all times we need to ping it at regular intervals. This is a cron job workflow file to keep my free render server always active. 

name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Conditional Ping for Render Backend Free Tier
        run: |
          HOUR=$(TZ=Asia/Kolkata date +'%H')

          # Convert hour to integer
          HOUR=$((10#$HOUR))

          if [ $HOUR -ge 7 ] || [ $HOUR -lt 1 ]; then
            # Active hours: Ping every 10 minutes
            echo "Active hours ($HOUR IST) → Pinging Render backend..."
            curl -s https://ai-powered-amount-extraction-in-medi-docs.onrender.com/api/health || true
          else
            # Night hours: Ping only if minute divisible by 30
            MIN=$(date +'%M')
            if [ $((10#$MIN % 30)) -eq 0 ]; then
              echo "Night hours ($HOUR:$MIN IST) → 30-min ping..."
              curl -s https://ai-powered-amount-extraction-in-medi-docs.onrender.com/api/health || true
            else
              echo "Night hours ($HOUR:$MIN IST) → Skipping ping to save minutes."
            fi
          fi
